import { Suspense } from "react";
import NavBar from "./components/Navbar";
import "./globals.css";

import localFont from "next/font/local";
import Loading from "./Loading";
import Footer from "./components/Footer";
// const Lato_Regular = localFont({ src: "./styles/fonts/Lato-Regular.ttf" });

const Lato_Regular = localFont({
  src: [
    {
      path: "././styles/fonts/Lato-Regular.ttf",
      weight: "400",
      style: "normal",
    },

    {
      path: "././styles/fonts/Lato-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Lato_Regular.className}>
        {" "}
        <NavBar />
        <Suspense fallback={<Loading />}>{children}</Suspense>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
